### ISSUE TITLE
Open to docker docs improvements?

### ISSUE THREAD

**Issue by chmac** [jelmer/xandikos#144]
I'm looking to run xandikos in docker. I'm not sure from the readme which paths I need to supply to docker, what ports it exposes, how SSL termination works, etc, etc. Assuming I can figure this stuff out, are you open to a PR to expand on the docker docs? I might also include an example docker-compose file.

**Comment by chmac** [comment]
I'll start gathering some notes here which I can turn into a PR later if you're in favour.

Example compose file

```yaml
version: "3.4"

services:
  xandikos:
    image: ghcr.io/jelmer/xandikos
    ports:
      - 8000:8000
    volumes:
      - /path/to/xandikos/data:/data
    restart: unless-stopped
```

Notes

- If you want to add data from an external tool, add it to git and commit the changes then xandikos will pick up the changes
- The docker container needs some kind of setup setup to create the address book, etc
  - `docker exec -it CONTAINER_NAME /code/bin/xandikos --defaults -d /data` probably works
- The docker container listens on port 8000 with no authentication
  - Point a reverse proxy here + add any authentication in front
- Quick & dirty way to test, use Thunderbird & the CardBook plugin (plus ssh port forwards if necessary)
- Filenames in the addressbook directory are the contact's UUID plus the `.vcf` extension
